#!/bin/bash

# ------------------------------------------------------------
# createToolChain
#
# Creates a new toolChain directory under toolChains/ and
# generates:
#   - .tchain file
#   - copied or empty tool configuration files
#   - tools.list file
#   - updated toolChainRegistry.txt
#
# Usage:
#   ./createToolChain.sh <toolChainName> <tool1> <tool2> ...
# ------------------------------------------------------------

updateToolChainRegistry()
{
    REGISTRY_FILE="toolChains/toolChainRegistry.txt"

    TOOLCHAIN_COUNT=0

    for DIR in toolChains/*; do
        if [ -d "$DIR" ]; then
            TOOLCHAIN_COUNT=$((TOOLCHAIN_COUNT + 1))
        fi
    done

    echo "Total toolChains: ${TOOLCHAIN_COUNT}" > "$REGISTRY_FILE"
    echo >> "$REGISTRY_FILE"

    for DIR in toolChains/*; do
        if [ -d "$DIR" ]; then
            CHAIN_NAME=$(basename "$DIR")

            echo "${CHAIN_NAME}:" >> "$REGISTRY_FILE"

            if [ -f "${DIR}/tools.list" ]; then
                while read -r TOOL_NAME; do
                    if [ -n "$TOOL_NAME" ]; then
                        echo "  ${TOOL_NAME}" >> "$REGISTRY_FILE"
                    fi
                done < "${DIR}/tools.list"
            else
                echo "  Warning: tools.list not found" >> "$REGISTRY_FILE"
            fi

            echo >> "$REGISTRY_FILE"
        fi
    done
}

if [ $# -lt 2 ]; then
    echo "Usage: ./createToolChain.sh <toolChainName> <tool1> <tool2> ..."
    exit 1
fi

if [ ! -d "tools" ] || [ ! -f "CMakeLists.txt" ]; then
    echo "Error: Please run this script from the project root directory."
    exit 1
fi

TOOLCHAIN_NAME=$1
TOOLCHAIN_DIR="toolChains/${TOOLCHAIN_NAME}"

shift
TOOLS=("$@")

if [ -d "$TOOLCHAIN_DIR" ]; then
    echo "Error: ToolChain already exists: $TOOLCHAIN_DIR"
    exit 1
fi

mkdir -p "$TOOLCHAIN_DIR"

CHAIN_FILE="${TOOLCHAIN_DIR}/${TOOLCHAIN_NAME}.tchain"
TOOLS_LIST_FILE="${TOOLCHAIN_DIR}/tools.list"

echo "# ToolChain: ${TOOLCHAIN_NAME}" > "$CHAIN_FILE"
echo "# Auto-generated by createToolChain.sh" >> "$CHAIN_FILE"
echo >> "$CHAIN_FILE"

> "$TOOLS_LIST_FILE"

for TOOL_NAME in "${TOOLS[@]}"; do

    TOOL_DIR="tools/${TOOL_NAME}"
    CONFIG_FILE="${TOOL_DIR}/config.ini"

    if [ ! -d "$TOOL_DIR" ]; then
        echo "Error: Tool does not exist: $TOOL_DIR"
        rm -rf "$TOOLCHAIN_DIR"
        exit 1
    fi

    DEST_CONFIG="${TOOLCHAIN_DIR}/${TOOL_NAME}.ini"

    if [ -f "$CONFIG_FILE" ]; then
        cp "$CONFIG_FILE" "$DEST_CONFIG"
    else
        echo "Warning: config.ini not found for tool: $TOOL_NAME"
        touch "$DEST_CONFIG"
    fi

    echo "./bin/${TOOL_NAME} ./${DEST_CONFIG}" >> "$CHAIN_FILE"
    echo "${TOOL_NAME}" >> "$TOOLS_LIST_FILE"

done

updateToolChainRegistry

echo
echo "ToolChain created successfully."
echo
echo "Created directory:"
echo "  $TOOLCHAIN_DIR"
echo
echo "Created files:"
echo "  $CHAIN_FILE"
echo "  $TOOLS_LIST_FILE"
echo "  toolChains/toolChainRegistry.txt"

for TOOL_NAME in "${TOOLS[@]}"; do
    echo "  ${TOOLCHAIN_DIR}/${TOOL_NAME}.ini"
done
